language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
 apt:
   sources:
     - llvm-toolchain-precise
     - ubuntu-toolchain-r-test
   packages:
     - g++-5
     - clang-3.8
     - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$CXX" == "clang++" && "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-clang llvm38; fi
  - if [[ "$CXX" == "g++" && "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-clang gcc5; fi
  # pwd ~> HOME/test
  - cd ./test

install:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [[ "$CXX" == "clang++" ]]; then export CXX="clang++" CC="clang"; fi
  - $CXX --version
  - cmake .

script:
  - make all
