# C++ 11/14 support
os: Visual Studio 2015

configuration: Release

# clone directory
clone_folder: c:\projects\promise2

before_build:
  - cd c:\projects\promise2\test
  - cmake -G "Visual Studio 14 2015 Win64"
  - dir

build:
  project: c:\projects\promise2\test\declfn.sln
